### ISSUE TITLE
[Feature Request] Private Player Notes on Entries

### ISSUE THREAD

**Issue by IlorinLorati** [WBHarry/pf2e-bestiary-tracking#106]
With the addition of both PCs and NPCs to the options of the bestiary, it would be really nice to provide the option for the player notes section to be per-player and potentially private, so they can record their thoughts about each other and the NPCs they encounter in a centralized location.

**Comment by Iankid** [comment]
my additional thought to this would be a drop down of registered users to switch between.
GM getting the full lists, and players get themselves or "general"

**Comment by WBHarry** [comment]
![image](https://github.com/user-attachments/assets/9261734b-9ebc-4795-903d-bf0dad602f53)
![image](https://github.com/user-attachments/assets/124cadc8-c761-4b9a-bc1e-c5fcf9a8415e)

Different ideas on the matter.

I'm not really sure if there is a need to make it dropdown selectable as in the one image though. I doubt there will be enough text for that to be an issue, especially since you can scroll the text.

When there are just a few notes, it's probably valuable to immediatey see both the group and private notes too at a glance.

**Comment by WBHarry** [comment]
Although I think I'm leaning away from the idea of this being a useful feature in the Bestiary. 
The Bestiary is generally about sharing information, and I don't really think this will be very useful. For the times when you want to have private notes about something, I honestly think a journal should do well.

**Comment by IlorinLorati** [comment]
I know that in my use case specifically, it would go a long way towards keeping player thoughts and information in a central location.

I'm running Season of Ghosts currently, and as a social-focused AP the players have a _lot_ of thoughts on the NPCs they've met so far, as well as each other. Being able to look through them at a glance instead of needing to open up and look and scroll through different journals would be huge for my personal QoL as the GM.

**Comment by IlorinLorati** [comment]
Fair enough, thanks for considering it.

**Comment by WBHarry** [comment]
Hope you find good use of the Bestiary all the same! 🤖 👍 
Closing the issue, as I don't plan to add private bestiary notes as is.
