### ISSUE TITLE
[Enhancement] Improve PC entry lead time

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#109]
The PC entries can have a notable load time if they haven't been viewed recently.
Not consistent.

**Comment by WBHarry** [comment]
I tested this out a bunch, and the sole cause of load time is the HTML Enrichment of ability descriptions (PCs have a -lot- more abilities typically). Removing text enrichment removes the initial load completly.

I'm going to see if I can limit enrichment to only visible text (since abilities have to be clicked open to actually display their descriptions regardless). If that works out it should be way faster.

**Comment by WBHarry** [comment]
I just released v1.0.10 that fixes what was mentioned above. It's removed any notable load time at all for PC imports or other entities with a lot of abilities from my testing. 🤖 👍
