### ISSUE TITLE
Feature request: reveal info to a specific player AKA per player bestiary

### ISSUE THREAD

**Issue by roi007leaf** [WBHarry/pf2e-bestiary-tracking#14]
It would be nice to have the option to separate the bestiary per player knowledge if it's possible to have as an optional setting

**Comment by WBHarry** [comment]
_< Suggestion after a discord conversation >_
---
I can see a potential appeal there.
In that case, there would need to be a toggle in the Creature View to set which players your actions will reveal things to - since I don't think anyone would stand a dialog popup every time to ask who it should be revealed to.
Essentially | **All** | **Player1** | **Player2** | **Player3** |, with All being the standard.

It could make the view confusing, even if it's only activated with an optional settings, but I'll give the idea a try at some point.

**Comment by uniwars** [comment]
could that be by PC instead of by player and using a recall knowledge macro for the player to ask a question that would add info/fake info to the bestiary page ? Like "what is its best saving throws ?", choose the skill to use to recall knowledge then macro check and add the info or a false one for that PC

**Comment by WBHarry** [comment]
I've done a bit of testing and thinking on this, and I don't think it's a usecase I want to support I'm afraid.
It's a bit of a UI nightmare to keep track of separate states of knowledge, and ultimately I don't think it should be a widely applicable usecase, since generally recalling knowledge and sharing it makes sense instead of keeping it secret for 10 seconds before revealing it.

Closing this issue. 🤖
