### ISSUE TITLE
Some monster info gets cut off on the left side. 

### ISSUE THREAD

**Issue by fishrobe** [WBHarry/pf2e-bestiary-tracking#18]
This module has quickly become one of my favorites. However, it seems there is a problem.

Most monsters work wonderfully but some get completely cut off on the left side, hiding their saves and other important information, as in the example below.  I have confirmed it happens with all other modules disabled.
 
![monster info cut off](https://github.com/user-attachments/assets/9c1418ea-f609-4cf1-9939-7d4491aa4b15)

It would be good if we could at least expand the box so we could see the cut off information.

EDIT: Upon some investigation, the two times this is happeneing are both with a Longbow in their inventory (the Erinys above and a Drider).  I added a longbow to another creature as an experiment and it also had information cut off on the left side, when without the longbow it was fine, so it seems like it's something to do with the length of the list of weapon traits, as the more traits a weapon has, the more cut off the left side becomes. Hope that helps.

**Comment by ThomaSutra** [comment]
The option to scroll the page with a mouse would work too

**Comment by WBHarry** [comment]
I haven't specifically done anything about this in the newly released v0.8.6 (it slipped my mind 🙄), but it's more useable now at least, since the left section of the creature view will not get pushed away anymore.
![image](https://github.com/user-attachments/assets/fc9db017-254c-4dc0-808c-1436c6f751b7)

I'm keeping this issue open since I need to handle the way the attack traits are getting cut off.

**Comment by WBHarry** [comment]
I just released v0.8.7.1. It fixes texts getting too long in general, so it shouldn't happen anymore. 
![image](https://github.com/user-attachments/assets/50c2f5ee-956a-47bb-ab9d-8a42c458e197)

Closing this issue. 😎👌
