### ISSUE TITLE
Pathfinder Ui - compatibility issue

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [WBHarry/pf2e-bestiary-tracking#2]
Launched the module with Pathfinder Ui enable but the Bestiary tracking is missing the sidebars etc for players to scroll through.

https://i.imgur.com/sxeCeIq.jpeg

Pathfinder Ui Settings
https://i.imgur.com/Q9Pa0dz.jpeg
https://i.imgur.com/rkFiEhB.jpeg
https://i.imgur.com/ykhuJqm.jpeg

**Comment by Sorellia** [comment]
I will springboard onto this since I was debugging this same issue; it's not just Pathfinder UI responsible for this, I was able to pin this down to the core setting to enable dark mode on the ui; if you have it set to dark mode (or set to mimic your browser and that's set to dark mode) the same issue occurs

**Comment by WBHarry** [comment]
It appears foundry's dark mode settings adds a `Overflow: Hidden` property to one of the application window classes, which makes the bookmarks become invisible.
I'll toss in a fix for that along with a searchbar for monsters within categories for a version improvement.

Actual good colour-scheme support will be looked at soon enough ✌️

**Comment by WBHarry** [comment]
The compatability issue with DarkMode, and by extension Pathfinder UI, has been fixed in the v0.8.2 release.
The colour schemes don't neccessarily mesh perfectly, but that's something I'll probably look at in an upcoming version.
