### ISSUE TITLE
Need a REVEAL ALL button

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#20]
Sometimes a party member knows everything about a creature and a button that reveals everything with one click would be very nice and convenient

**Comment by WBHarry** [comment]
I just released v0.8.9.8. It adds a `Reveal Creature` and `Hide Creature` pair of buttons to the Bestiary context menu for revealing or hiding everything on the current creature at once. 🥳 
![image](https://github.com/user-attachments/assets/eb9942b9-4b05-4b3a-8df2-d2e6b8bd6d03)

**Comment by ThomaSutra** [comment]
Thank you.

I feel foolish, but I can't find the Bestiary Context Menu. 

Also, when I look to the Side bar and click on notes, the link to the bestiary is no longer there. I can only access it through the bestiary. Could the 2 be related?

**Comment by WBHarry** [comment]
Ah, no the button has been moved. It's now found in the right menu under Actors.
![image](https://github.com/user-attachments/assets/e179a744-5ddf-4d87-a113-890d05d5b894)

The context menu is up in the top right corner of the Bestiary view. It's only visible for the GM at the moment, since all the functions currently in it are GM only. 
![image](https://github.com/user-attachments/assets/2a005917-26df-4c8c-9331-11e0b3e67a8a)

It's worth noting that I've added the ability to bind hotkeys now aswell. So GM and players can for instance now bind opening the Bestiary to something like 'B' :grin:
![image](https://github.com/user-attachments/assets/97c9a16b-d010-4fba-904c-2976a482bb9c)

**Comment by ThomaSutra** [comment]
Just checked this and still no reveal all. 

just 3 choices: 
Refresh Bestiary
Data save slots
Reset Bestiary

NO reveal creature option

can there be a reveal all button at the top of each creature, say, next to the name?

**Comment by WBHarry** [comment]
The buttons do exist. They're only present if you are actually viewing a creature though, incase you only checked it on the homepage of the Bestiary.
![image](https://github.com/user-attachments/assets/4a3dfd6e-92b9-4c20-8c7c-45a57c272d2e)

**Comment by WBHarry** [comment]
I really don't want to put a button next to the name as I don't feel it will be that frequently used of a feature, and definately not something you want missclicked.

**Comment by ThomaSutra** [comment]
Okay, I got it now. Thanks
