### ISSUE TITLE
[Bug] No macros in compendium in latest version of Bestiary Tracker

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#33]
The compendium contains zero macros.

**Comment by WBHarry** [comment]
Hm, yeah it's gone missing. Strange. I'll add it back for the next version, but I'll have to look over how I bundle the macros since something seems a bit unstable about it.

If you need them before the next version they're quite simple:

**Open Bestiary**: `game.modules.get('pf2e-bestiary-tracking').macros.openBestiary();`
**Show Monster**: `game.modules.get('pf2e-bestiary-tracking').macros.showMonster();`

**Comment by fishrobe** [comment]
> Hm, yeah it's gone missing. Strange. I'll add it back for the next version, but I'll have to look over how I bundle the macros since something seems a bit unstable about it.
> 
> If you need them before the next version they're quite simple:
> 
> **Open Bestiary**: `game.modules.get('pf2e-bestiary-tracking').macros.openBestiary();` **Show Monster**: `game.modules.get('pf2e-bestiary-tracking').macros.showMonster();`

Thanks for this! Was about to copy them from the world I alreaady have set up, but this is easier lol. Glad I came here to check first.

**Comment by WBHarry** [comment]
I just released v0.8.8 and macros are back and here to stay. I automated the build pipeline, so I can't screw it up 😆
