### ISSUE TITLE
[Bug] Display issues with new styling

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#39]
Screenshots attached. As you can see, when light mode is on, the monster type tabs are very difficult to see, particularly against a dark background. When dark mode is on, the actual page is impossible to read.
<img width="900" alt="Screenshot 2024-08-18 at 4 53 21 PM" src="https://github.com/user-attachments/assets/06eb091b-d92a-4881-a984-8dc301139de2">
<img width="900" alt="Screenshot 2024-08-18 at 4 53 39 PM" src="https://github.com/user-attachments/assets/0ce4f7c4-6e65-4bb9-a5ea-efec99bdb0c4">

**Comment by WBHarry** [comment]
That's Dorako Light Core and Dorako Dark Core, correct?

**Comment by weepingminotaur** [comment]
It's just me changing the core Foundry setting (Preferred Color Schemes) from light to dark. But yes, I do have Dorako on.

**Comment by weepingminotaur** [comment]
My sheet theme setting for Dorako is CRB Light.

**Comment by WBHarry** [comment]
Hm. I'm not going to do any more serious styling work as is, since it's quite possibly Dorako is going to give me a hand one of these weeks.
But looking at it, it is literally one css property that is making it rough for the dark mode. Disabling just that gives you this instead.
![image](https://github.com/user-attachments/assets/437da9b6-d578-4eff-9da1-4c965c9b4ecc)
![image](https://github.com/user-attachments/assets/a2390f3f-9b41-46fc-8a42-2a498e66af32)
![image](https://github.com/user-attachments/assets/5f71ffa6-d16c-48b1-8d91-8a247935f36e)


I can see if I can add a small style checking for Dorako just to disable that tiny thing

**Comment by WBHarry** [comment]
There we go. I released v0.8.8.1 with that little styling stopgap. I think all the Dorako versions except `Discord Light` and maybe something else looked good now.
Not official support for Dorako yet mind you, but it shouldn't mess things up normally now :grin:

**Comment by weepingminotaur** [comment]
Thank you!!
