### ISSUE TITLE
Suggestion: Option to make the creature name revealable

### ISSUE THREAD

**Issue by xdy** [WBHarry/pf2e-bestiary-tracking#4]
If enabled, set the player-visible name to, say, 'Unknown Creature' until the GM reveals it. (Would work well with #1 )

**Comment by WBHarry** [comment]
I just released v0.8.2. Creatures names are now hidden by default with the GM able to reveal them. If they are not revealed, they are shown as 'Unknown Creature' 🥷

**Comment by WBHarry** [comment]
@Mermut 
I'm not certain I personally see the need to add creatures ahead of time with hidden names and pictures. The way I see it:
- It doesn't seem like it'd be valuable for the players to have the Bestiary cluttered with unknowable entries they haven't even seen before
- It wouldn't really making anything faster since the GM can just drag something in right away (or just start a combat with the creatures present) to add them. 
- There is no data entry required with the module after all, so preparation doesn't really make sense. Anything data you click on in the Bestiary is revealed to players right away.

I will close this issue as it's been added. But if you do think it would be a helpful feature to be able to hide the picture, then feel free to make a new Issue on the matter. 😸
