### ISSUE TITLE
Entire Entries Disappear whenver you do an update

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#40]
LAst update, I noticed that about half of the Entries I made into the bestiary would no longer open. I had to delete them and re add each one.

So, when I did the update today, I checked to see if the problem reoccurred. 

Instead, Entire entries have disappeared.

**Comment by WBHarry** [comment]
Oouf. Sorry about this. 😞 
This is not going to be a thing going forward, but the entries that disappeared did so because their data model was too old to salvage going forward (no proper link back to the creature they were created from).

I'm going to take this time to create a data filled test world to keep a copy around of to more seriously test for migration issues with Bestiary entries to avoid things like this. Sadly nothing that can be done to restore the data, you will simply have to drag the creatures in again.
