### ISSUE TITLE
[Feature Request] Add Unique as a new optional tab

### ISSUE THREAD

**Issue by elemorelli** [WBHarry/pf2e-bestiary-tracking#59]
I'd love to have special creatures on a separate tab (maybe at the end of the list?) to track creatures with Unique rarity.

Something like this?
![image](https://github.com/user-attachments/assets/2ee1c50a-d3ed-4fc9-bfc6-4953e1b14e65)

 Or a maybe a rarity filter?

**Comment by WBHarry** [comment]
Rarity is something I haven't added anything about yet. I should definately do -something- regarding that. 🤔 

For the moment. Yup, you can make it somewhat work as is by adding Unique as a creature trait in the system, then as a creature type in the module settings so it appears as a category 😁

**Comment by WBHarry** [comment]
I think with the way the Bestiary has developed by now, adding this as a directly supported feature isn't really feasible.

I'm not going to support a category with Unique creatures, but as mentioned you can easily achieve that effect yourself:
1) Add a homebrew creature trait in the system homebrew
![image](https://github.com/user-attachments/assets/3903f32a-6065-43a4-8a16-a59bc45298f6)

2) Add the homebrewed creature trait as a creature category in the module settings
![image](https://github.com/user-attachments/assets/a372be8a-bb06-440f-bb67-25f93e7adaa1)

3) Tag creatures with it and drag them into the Bestiary. Probably want to swap the NPC Recognition setting aswell so that NPCs are recognised by an NPC tag instead of Unique rarity for this use-case.
![image](https://github.com/user-attachments/assets/d4727b8e-5f97-428e-9885-3f499c3abd92)

I'm closing this issue, and hope you find this a workable solution 🤖 ✌️
