### ISSUE TITLE
[BUG] Can't add any NPCs to NPC Gallery

### ISSUE THREAD

**Issue by SonofOrion42** [WBHarry/pf2e-bestiary-tracking#67]
Whenever I try to drag a character over to the NPC Gallery, it doesn't work; they get added to the creature bestiary instead. I cannot figure out why this is happening, I have the NPC Gallery open and everything, and there aren't any buttons I could use to add any NPCs on the window... so I'm at a complete loss. There are no error logs in the console, either.

**Comment by WBHarry** [comment]
Heya. NPCs are identifed by the Bestiary based on a module setting
![image](https://github.com/user-attachments/assets/05b3ae0c-4d16-4899-b844-73998fea1554)

By default it checks for the Unique rarity, but you might prefer using a NPC tag that you add to an NPCs traits.  Aslong as the creature you drag in matches the NPC criteria, it is added to the Unaffiliated category in the NPC Gallery - and once you click into it you can then add it to any NPC Categories that you create.

There is no difference between a creature and an NPC in the pf2e system, which is why a distinction like this is neccessary 😁

**Comment by SonofOrion42** [comment]
Ahhhhh. This explains a lot. Thank you!

**Comment by SonofOrion42** [comment]
Though I seem to have run into a new issue: none of the party members are showing up in an NPC's Dispositions tab. Am I missing something?

**Comment by WBHarry** [comment]
The way I implemented it in this version is that it will only show the players that are currently active in the world.
I did it this way because I thought it made sense to support GMs that run multiple groups in one world, so that all the inactive players from other groups don't show up.

I'll probably change it though so that GMs still see the full list - or the current active party (which they can toggle).

**Comment by WBHarry** [comment]
I just released v0.9.4. It makes a change so that the currently active party is always displayed in the Dispositions sections. If you have multiple groups, then you can have multiple parties and just change which one is active depending on who is playing 👍
